version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - '3000:3000'
    networks:
      - appnet
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://backend:3000/api
        - VITE_SOCKET_URL=http://backend:3000
    container_name: frontend
    env_file:
      - ./frontend/.env
    environment:
      - VITE_API_URL=http://backend:3000/api
      - VITE_SOCKET_URL=http://backend:3000
    ports:
      - '5173:5173'
    depends_on:
      - backend
    networks:
      - appnet
networks:
  appnet:
    driver: bridge 